# Practical_6: Numpy

---



In [2]:
# Global importation of numpy
import numpy as np

### Exercise 1:
Create a NumPy array of integers from 1 to 10.



In [2]:
arr_1 = np.arange(1, 11)

print(arr_1)

[1 2 3 4 5 6 7 8 9]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.



In [3]:
arr_2 = np.zeros((3,3), dtype=int)
print(arr_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.



In [6]:
arr_3 = np.linspace(0, 5, 10)
print(arr_3)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.



In [4]:
arr_4 = np.eye(5)
print(arr_4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.



In [9]:
arr_5 = np.random.random(size=(4,4))
arr_5

array([[0.10766007, 0.43465087, 0.43594775, 0.06878045],
       [0.14907564, 0.23059946, 0.73086749, 0.75202604],
       [0.27272877, 0.09146698, 0.85594369, 0.35919638],
       [0.59791601, 0.32506971, 0.46799549, 0.52374055]])

In [29]:
np.random.seed(10)

A = np.random.rand(4,4)
print(A)

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]


In [30]:
np.random.seed(0)

A = np.random.rand(4,4)
print(A)

[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


In [32]:
A = np.random.rand(4,4)
print(A)

[[0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369]]


### Exercise 6:
Find the shape of a NumPy array.



In [10]:
# Taking array 5 as a case study

shape_arr_5 = arr_5.shape
print(shape_arr_5)

(4, 4)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [15]:
arr_61d = np.random.random(16)
print(arr_61d)


arr_61d = arr_61d.reshape(4,4)
print(arr_61d)

[0.66466201 0.98680201 0.61681605 0.85838945 0.37413289 0.2210334
 0.87285313 0.80006862 0.41043326 0.94511739 0.01299138 0.91639767
 0.87236837 0.09846056 0.10430629 0.52121421]
[[0.66466201 0.98680201 0.61681605 0.85838945]
 [0.37413289 0.2210334  0.87285313 0.80006862]
 [0.41043326 0.94511739 0.01299138 0.91639767]
 [0.87236837 0.09846056 0.10430629 0.52121421]]


### Exercise 8:
Find the data type of the elements in a NumPy array.



In [17]:
# Taking array 7 as a case study
print(type(arr_61d))

print(arr_61d.dtype)


<class 'numpy.ndarray'>
float64


### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.



In [35]:
# arr_7 = np.arange(1, 101)

even_7 = np.array([num for num in np.arange(1,101) if num%2==0])
print(even_7)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
# Another Solution

In [37]:
even_9b = np.arange(2, 101, 2)
print(even_9b)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.



In [22]:
arr_10 = np.random.randint(10, 60, size=(6, 6))

print(arr_10)

[[23 24 41 17 40 27]
 [38 21 20 24 20 52]
 [25 46 29 25 48 11]
 [53 43 30 49 40 53]
 [29 50 17 16 35 48]
 [14 15 52 43 10 47]]


### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [24]:
arr_11 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_11b = arr_11[:, 2] # This means give me all the rows in column 3 (whose index is zero)
print(arr_11b) 

[3 6 9]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [25]:
# Taking array 11 as a reference

sum_11 = np.sum(arr_11)
print(sum_11)

45


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.



In [27]:
arr_13 = np.random.randint(10, 50, size=(3,3))

print(arr_13)

mean_13 = np.mean(arr_13)

median_13 = np.median(arr_13)

std_dev_13 = np.std(arr_13)

print("Mean:", mean_13)
print("Median:", median_13)
print("Standard Deviation:", std_dev_13)

[[12 48 24]
 [34 15 31]
 [21 47 11]]
Mean: 27.0
Median: 24.0
Standard Deviation: 13.232955494186138


### Exercise 14:
Find the maximum and minimum values in a NumPy array.



In [39]:
arr_14 = np.random.randint(0, 90, size=(5,5))
print(arr_14)

max_14 = np.max(arr_14)

min_14 = np.min(arr_14)

print("Maximum:", max_14)

print("Minimum:", min_14)

[[64 69  0 50 36]
 [34 48  3 42 77]
 [21 73  0 10 43]
 [58 23 59  2 62]
 [35 67 82 46 20]]
Maximum: 82
Minimum: 0


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [48]:
arr_15 = np.random.randint(100, size=(20,))

print(arr_15)

max_index_15 = np.argmax(arr_15)

print("Index of Maximum:", max_index_15)
print("Value of Maimum:", arr_15[max_index_15])

# min_index_15 = np.argmin(arr_15)
# print("Index of Minimum:", min_index_15)

# print("Maximum:", arr_15[max_index_15])
# print("Minimum: ", arr_15[min_index_15])

[39 61 85 97 44 34 34 88 33  5 36  0 75 34 69 53 80 62  8 61]
Index of Maximum: 3
Value of Maimum: 97


In [ ]:
### Exercise 16:
Create a NumPy array and reverse its elements.



In [52]:
arr_16 = np.arange(1,11)
print(arr_16)

#reversed array

reversed_arr_16 = arr_16[::-1]
print(reversed_arr_16)
print(type(reversed_arr_16))

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
<class 'numpy.ndarray'>


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.



In [59]:
arr_17a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_17b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

arr_17c = arr_17a * arr_17b
# arr_17cii = arr_17a.dot(arr_17b) #not matrix multiplication
arr_17cii = np.multiply(arr_17a, arr_17b) #elementwise multiplication

print(arr_17c)
print(arr_17cii)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
### Exercise 18:
Create a diagonal matrix from a given 1D array.



In [62]:
arr_18 = np.array([1, 2, 3])

diagonal_arr_18 = np.diag(arr_18)
print(diagonal_arr_18)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [64]:
arr_19a = np.array([[1,3], [3,7]])
arr_19b = np.array([[2,4], [6, 8]])

arr_19c = np.dot(arr_19a, arr_19b)

print(arr_19c)

[[20 28]
 [48 68]]


In [ ]:
### Exercise 20:
Flatten a 2D NumPy array into a 1D array.



In [86]:
# make a 2d array
arr_20 = np.arange(1, 101, 1)
arr_20a = arr_20.reshape(10,10)

print(arr_20a, arr_20a.size) # to see how the array is reshaped and to see its size

print(arr_20.size) # This returns the length of the array

# flattened array
arr_20b = arr_20a.reshape(arr_20a.size,)
print(arr_20b)

# or we can flatten the array with
print(arr_20a.flatten())

# Test for equivalence
print(np.array_equal(arr_20, arr_20b)) # should return True
# print(arr_20 == arr_20b) # returns True for all the elements
# print(arr_20a.flatten() == arr_20b) # should return True for all the elements

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] 100
100
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38

In [ ]:
### Exercise 21:
Stack two NumPy arrays vertically.



In [91]:

arr_21a  = np.array([1,2,3,4,5])

arr_21b  = np.array([6,7,8,9,10])

arr_21c = np.vstack((arr_21a, arr_21b)) #or
# arr_21c = np.concatenate((arr_21a, arr_21b), axis=1) #gives horizontal stacking for 1d arrays, but for 2d arrays, gives vertical stacking
# arr_21c = np.concatenate((arr_21a[np.newaxis, :], arr_21b[np.newaxis, :]), axis=0) # tricks the concatenation into believeing that we're stacking 2d arrays, so gives vertical stacking
# but all in all, vstack is the desired choice.

print(arr_21c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
### Exercise 22:
Stack two NumPy arrays horizontally.


In [92]:
arr_22a  = np.array([1,2,3,4,5])

arr_22b  = np.array([6,7,8,9,10])

arr_22c = np.hstack((arr_22a, arr_22b))
print(arr_22c)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
### Exercise 23:
Split a NumPy array into multiple sub-arrays.



In [110]:
arr_23a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

# arr_23b = np.hsplit(arr_23a, 5) # This performs columwise splitting

# print(arr_23b)

# for i, arr in enumerate(arr_23b):
#     print(f'Sub-array {i+1}:')
#     print(arr)
#     print('---')

# or 
arr_23c = np.split(arr_23a, 3, axis=0) # column wise split, use number of rows probably similar to vsplit()
arr_23d = np.split(arr_23a, 5, axis=1) # column wise split, for rowwise split, use number of columns, this is similar to hsplit()
# print(arr_23c)
print("Columnwise: ", arr_23c)
print("Rowwise: ", arr_23d)

Columnwise:  [array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]])]
Rowwise:  [array([[ 1],
       [ 6],
       [11]]), array([[ 2],
       [ 7],
       [12]]), array([[ 3],
       [ 8],
       [13]]), array([[ 4],
       [ 9],
       [14]]), array([[ 5],
       [10],
       [15]])]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.



In [113]:
arr_24 = np.random.rand(5,5)

print("Original Array:")
print(arr_24)

print("\nArray with rounded elements:")
arr_24_rounded = np.round(arr_24, 2)

print(arr_24_rounded)

Original Array:
[[0.73085581 0.25394164 0.21331198 0.51820071 0.02566272]
 [0.20747008 0.42468547 0.37416998 0.46357542 0.27762871]
 [0.58678435 0.86385561 0.11753186 0.51737911 0.13206811]
 [0.71685968 0.3960597  0.56542131 0.18327984 0.14484776]
 [0.48805628 0.35561274 0.94043195 0.76532525 0.74866362]]

Array with rounded elements:
[[0.73 0.25 0.21 0.52 0.03]
 [0.21 0.42 0.37 0.46 0.28]
 [0.59 0.86 0.12 0.52 0.13]
 [0.72 0.4  0.57 0.18 0.14]
 [0.49 0.36 0.94 0.77 0.75]]


### Exercise 25:
Find the unique elements of a NumPy array.


In [114]:

arr_25 = np.array([1, 2, 3, 2, 3, 4, 5, 6, 2, 3])

unique_arr_25 = np.unique(arr_25)

print("Original Array:")

print(arr_25)

print("\nUnique Elements:")

print(unique_arr_25)

Original Array:
[1 2 3 2 3 4 5 6 2 3]

Unique Elements:
[1 2 3 4 5 6]


In [ ]:
### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [9]:
# We can do this in two ways:
# 1. Where?
arr_26 = np.random.randint(1, 20, size=(20,))

print("Original Array")
print(arr_26)

arr_26 = np.where(arr_26<6, 6, arr_26)

print("Replaced Array")
print(arr_26)

Original Array
[13  8 15  7  1  3  1 10  4 11 14  1  6 16 12 16  9  5 14  2]
Original Array
[13  8 15  7  6  6  6 10  6 11 14  6  6 16 12 16  9  6 14  6]


In [13]:
# 2. Booloean Mapping
arr_26b = np.random.randint(1,20, size=(20,))

print("Original Array")
print(arr_26b)

arr_26b[arr_26b < 6] = 6

print("Replaced AArray")
print(arr_26b)

Original Array
[17 10 10 18 11  2 17  6  5 15 13  1  9 13 16  3  2  3 12  1]
Replaced AArray
[17 10 10 18 11  6 17  6  6 15 13  6  9 13 16  6  6  6 12  6]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [19]:
arr_27 = np.arange(1, 15)

print(arr_27)

cummulative_sum = np.cumsum(arr_27)
print(cummulative_sum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [20]:
arr_28 = np.array([[1, 0, 3], [0, 4, 0], [5, 0, 0]])

print(arr_28)

non_zero_elements = np.count_nonzero(arr_28)

print(f"Number of non-zero elements: {non_zero_elements}")

[[1 0 3]
 [0 4 0]
 [5 0 0]]
Number of non-zero elements: 4


In [ ]:
### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [30]:
arr_29 = np.random.randint(10, size=(10,))

print(arr_29)

sorted_arr_29 = np.sort(arr_29)

print(sorted_arr_29)

[9 8 9 4 3 0 3 5 0 2]
[0 0 2 3 3 4 5 8 9 9]


### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [38]:
matrix_30 = np.array([[1,2,3], [4,5,6], [7,8,9]])

row_sums_30 = np.sum(matrix_30, axis=1)

column_sums_30 = np.sum(matrix_30, axis=0)

print("Row Sums:")

print(row_sums_30)

print("Column Sums:")

print(column_sums_30)

Row Sums:
[ 6 15 24]
Column Sums:
[12 15 18]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [42]:
# Min-Max Method...

np.random.seed(45)

array_31 = np.random.randint(1, 10, size=(2, 5))

print("Original Array:")

print(array_31)


normalized_array_31 = (array_31 - np.min(array_31)) / (np.max(array_31) - np.min(array_31))

print("Normalized Array:")

print(normalized_array_31)

Original Array:
[[4 1 6 4 5]
 [9 2 6 7 9]]
Normalized Array:
[[0.375 0.    0.625 0.375 0.5  ]
 [1.    0.125 0.625 0.75  1.   ]]


In [43]:
# Z score method standardizes
np.random.seed(45)
array_31b = np.random.randint(1, 10, size=(2, 5))

print("Original Array:")

print(array_31b)

mean_31b = np.mean(array_31b)

std_dev_31b = np.std(array_31b)

normalized_array_31b = (array_31b - mean_31b) / std_dev_31b

print("Normalized Array:")

print(normalized_array_31b)

Original Array:
[[4 1 6 4 5]
 [9 2 6 7 9]]
Normalized Array:
[[-0.51346913 -1.69839789  0.27648338 -0.51346913 -0.11849288]
 [ 1.46141214 -1.30342163  0.27648338  0.67145963  1.46141214]]


In [ ]:
### Exercise 32:
Create two NumPy arrays and find the dot product.



In [45]:
arr_31a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

arr_31b = np.array([[17,18,19,20], [21,22,23,24], [25,26,27,28], [29,30,31,32]])

dot_product_31 = np.dot(arr_31a, arr_31b)

print(dot_product_31)

[[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]


### Exercise 33:
Find the trace of a square NumPy matrix.


In [66]:
arr_33 = np.random.randint(16, size=(3,3))

print(arr_33)

trace_33 = np.trace(arr_33)

print(f"Trace of the matrix: {trace_33}")

[[ 4 15  6]
 [ 4  9 13]
 [15  1  6]]
Trace of the matrix: 19


### Exercise 34:
Create a 2D array and swap two rows.


In [63]:
arr_34 = np.array([[1,2,3], [4,5,6], [7,8,9]])

print("Original Array:")

print(arr_34)

arr_34[[1,2]] = arr_34[[2,1]] # swaps row to with row three

print("Swapped Array:")

print(arr_34)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Swapped Array:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [62]:
# Playing Aroun
# # arr_34[[0, 2]]
# arr_34[0:3] = arr_34[[2, 1, 0]]

# print(arr_34)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [69]:
arr_35 = np.array([x for x in range(2,16) if x%3 == 0])
print(arr_35)

column_vector_35 = arr_35[:, np.newaxis]

print(column_vector_35)

[ 3  6  9 12 15]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]]


In [70]:
# Or

column_vector_35b = arr_35.reshape(-1, 1)

print(column_vector_35b)

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]]


In [71]:
column_vector_35c = np.atleast_2d(arr_35).T
print(column_vector_35c)

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]]


### Exercise 36:
Find the determinant of a 3x3 matrix.


In [75]:
np.random.seed(0)

# matrix_36 = np.random.randint(1, 45, size=(3, 3))
matrix_36 = np.array([[1,0,0], [0,6,0], [0,0,9]], dtype=np.int32)

print(matrix_36)

print("Determinant:", np.linalg.det(matrix_36)) # Why is the decimal place like this?

[[1 0 0]
 [0 6 0]
 [0 0 9]]
Determinant: 54.00000000000001


### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [76]:
# Create a 2 by 2 matrix

matrix_37 = np.array([[2, -1], [-1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(matrix_37)

print("Eigenvalues:")

print(eigenvalues)

print("Eigenvectors:")

print(eigenvectors)

Eigenvalues:
[3. 1.]
Eigenvectors:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


### Exercise 38:
Solve a system of linear equations using NumPy.


In [ ]:
# Create the coefficient matrix and the constant vector 

coefficient_matrix = np.array([[2, 3], [-1, 4]])

constant_vector = np.array([5, 6])

solution = np.linalg.solve(coefficient_matrix, constant_vector)

print("Solution:")

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [85]:
np.random.seed(0)

arr_39 = np.random.randint(1, 100, size=(4, 4))

print("Original Array:")

print(arr_39)

noise_level = 10

# print(arr_39.shape)

noisy_array_39 = arr_39 + np.random.normal(scale=noise_level, size=arr_39.shape)

print("Noisy Array:")

print(noisy_array_39)

Original Array:
[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]]
Noisy Array:
[[46.44043571 62.54273507 72.61037725 69.21675016]
 [72.43863233 13.33674327 98.94079073 19.94841736]
 [40.13067702 79.45904261 45.47010184 95.53618595]
 [97.64436199  5.5783498  81.69754624 51.45634325]]


In [ ]:
### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.



In [92]:
arr_40 = np.array([[1,4,7], [11,44,77], [111, 444, 777]])

diag_40 = np.diag(arr_40).reshape(1,-1).T # i intentionally added the .reshape(1,-1).T to transpose the row vector initially returned

print(diag_40)

[[  1]
 [ 44]
 [777]]


In [ ]:
### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [95]:
np.random.seed(0)

arr_41 = np.random.randint(1, 100, size=100)

print("Original Array:")
print(arr_41)

print("Clipped Array:")
clipped_arr_41 = np.clip(arr_41, a_min=10, a_max=50)

print(clipped_arr_41)

Original Array:
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89 82 38 26 78
 73 10 21 81 70 80 48 65 83 89 50 30 20 20 15 40 33 66 10 58 33 32 75 24
 36 76 56 29 35  1  1 37 54  6 39 18 80  5 43 59 32  2 66 42 58 36 12 47
 83 92  1 15 54 13 43 85 76 69  7 69 48  4 77 53 79 16 21 59 24 80 14 86
 49 50 70 42]
Clipped Array:
[45 48 50 50 50 10 50 22 37 50 50 50 50 13 50 50 40 50 47 50 50 38 26 50
 50 10 21 50 50 50 48 50 50 50 50 30 20 20 15 40 33 50 10 50 33 32 50 24
 36 50 50 29 35 10 10 37 50 10 39 18 50 10 43 50 32 10 50 42 50 36 12 47
 50 50 10 15 50 13 43 50 50 50 10 50 48 10 50 50 50 16 21 50 24 50 14 50
 49 50 50 42]


In [ ]:
### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [96]:
arr_42 = np.array([[1, -2, 3], [-4, 5, -6], [7, 8, -9]])

print("Original Array:")

print(arr_42)

arr_42[arr_42 < 0] = 0


print("Modified Array:")

print(arr_42)

Original Array:
[[ 1 -2  3]
 [-4  5 -6]
 [ 7  8 -9]]
Modified Array:
[[1 0 3]
 [0 5 0]
 [7 8 0]]


In [ ]:
### Exercise 43:
Find the inner and outer products of two NumPy arrays.




In [98]:
arr_43a = np.array([1, 2, 3, 4,5,6])

arr_43b = np.array([7, 8, 9,10, 11, 12])

inner_prod_ab43 = np.inner(arr_43a, arr_43b)
 
outer_prod_ab43 = np.outer(arr_43a, arr_43b)

print("Inner Product (AB):", inner_prod_ab43)

print("Outer Product (AB):", outer_prod_ab43)

Inner Product (AB): 217
Outer Product (AB): [[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]


In [ ]:
### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---



In [ ]:
### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---


In [ ]:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---


In [ ]:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---
